# docker-compose.yml
version: '3'


networks:
  satc-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"
          
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    depends_on:
      - db
    networks:
      - satc-network

  opcua_server:
    image: python:3.10.12-slim
    volumes:
      - ./opcua_server.py:/opcua_server.py
      - ./opcua_client.py:/opcua_client.py
      - ./requirements.txt:/requirements.txt
    command: python /opcua_server.py
    ports:
      - "4840:4840"
    networks:
      - satc-network
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: /bin/bash -c "pip install --no-cache-dir -r /requirements.txt && exec $$0 $$@"

  opcua_client:
    image: python:3.10.12-slim
    volumes:
      - ./opcua_client.py:/opcua_client.py
      - ./requirements.txt:/requirements.txt
    command: python /opcua_client.py
    networks:
      - satc-network
    depends_on:
      - opcua_server
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: /bin/bash -c "pip install --no-cache-dir -r /requirements.txt && exec $$0 $$@"

  db:
    image: postgres:latest
    ports:
      - "54321:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      satc-network:
        ipv4_address: "172.18.0.6"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  adminer:
    image: adminer
    ports:
      - "8085:8080"
    networks:
      - satc-network
  frontend:
    build: ../satc-frontend
    ports:
      - "80:80"
    networks:
      - satc-network
